# Default Configuration File for MobFighter!
# Made by Grasinga.
# WorldName should be whatever world you are wanting the plugin to work on.
# CurrentNight is what night it is currently.
# EventNight is the night that events occur on. Default is every 5 nights.
# Creative Immunity is for OPs (It allows you to bypass being set to Survival after anvil repair/combine.)
# MobDrops are the ids of the item you want to sell. 
# MobDropPrice is the amount you want the corresponding item in MobDrops spot to cost.
# First spot in MobDrops is WRITTEN_BOOK. The First spot in MobDropPrice is 0, so WRITTEN_BOOK sells for $0.
# WRITTEN_BOOK is in there to sell back the books a player has read. (Frees up inventory space.)
World Name: world
Current Night: 0
Event Night: 5
Creative Immunity:
- Grasinga
Top Player: Grasinga
MobDrops:
- WRITTEN_BOOK
- IRON_INGOT
- GOLD_INGOT
- DIAMOND
- STRING
- SULPHUR
- BONE
- ROTTEN_FLESH
- ENDER_PEARL
- GLASS_BOTTLE
- SPIDER_EYE
- CARROT_ITEM
- POTATO_ITEM
- GLOWSTONE_DUST
- SUGAR
- STICK
- ARROW
- REDSTONE
- GOLD_RECORD
- GREEN_RECORD
- RECORD_3
- RECORD_4
- RECORD_5
- RECORD_6
- RECORD_7
- RECORD_8
- RECORD_9
- RECORD_10
- RECORD_11
- RECORD_12
- DRAGON_EGG
- SKULL_ITEM
MobDropPrice:
- 0
- 50
- 5
- 100
- 3
- 3
- 3
- 3
- 20
- 10
- 3
- 20
- 20
- 20
- 20
- 20
- 1
- 20
- 1000
- 1000
- 1000
- 1000
- 1000
- 1000
- 1000
- 1000
- 1000
- 1000
- 1200
- 1000
- 2500
- 1500